# Worksheet‑1 – Maths (Kinjalk Pokharel)


## Problem 1 – Basic Array Initialization

In [1]:
import numpy as np
empty_arr = np.empty((2,2))
empty_arr


array([[ 0.00000000e+000, -2.71668937e-311],
       [ 0.00000000e+000,  0.00000000e+000]])

In [2]:
ones_arr = np.ones((4,2))
ones_arr


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
filled_arr = np.full((3,3), 7)
filled_arr


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [4]:
A = np.array([[1,2,3],[4,5,6]])
zeros_like_A = np.zeros_like(A)
zeros_like_A


array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
ones_like_A = np.ones_like(A)
ones_like_A


array([[1, 1, 1],
       [1, 1, 1]])

In [6]:
new_list = [1,2,3,4]
np.array(new_list)


array([1, 2, 3, 4])

## Problem 2 – Numerical Ranges and Array Indexing

In [7]:
arr_10_49 = np.arange(10,50)
arr_10_49


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
matrix_0_8 = np.arange(9).reshape(3,3)
matrix_0_8


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)


In [ ]:
rand_30 = np.random.random(30)
rand_30.mean()


In [ ]:
rand_10x10 = np.random.random((10,10))
rand_10x10.min(), rand_10x10.max()


In [ ]:
arr = np.zeros(10)
arr[4] = 1
arr


In [ ]:
arr = np.array([1,2,0,0,4,0])
arr[::-1]


In [ ]:
border_arr = np.ones((6,6))
border_arr[1:-1,1:-1] = 0
border_arr


In [ ]:
checker = np.zeros((8,8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
checker


## Problem 3 – Array Operations

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])


In [ ]:
x + y


In [ ]:
x - y


In [ ]:
x * 3


In [ ]:
x**2


In [ ]:
v_dot_w = np.dot(v,w)
x_dot_v = np.dot(x,v)
x_dot_y = np.dot(x,y)
v_dot_w, x_dot_v, x_dot_y


In [ ]:
xy_row = np.vstack((x,y))
vw_col = np.column_stack((v,w))
xy_row, vw_col


In [ ]:
try:
    np.concatenate((x,v))
except Exception as e:
    e


## Problem 4 – Matrix Operations

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A @ np.linalg.inv(A)


In [ ]:
A @ B, B @ A


In [ ]:
left = (A@B).T
right = B.T @ A.T
left, right


 linear equations 

In [ ]:
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])
solution = np.linalg.solve(A,B)
solution


In [ ]:
sol_via_inverse = np.linalg.inv(A) @ B
sol_via_inverse
